const CREATE = 'article/CREATE'
const CREATE_SUCCESS = 'article/CREATE_SUCCESS'
const CREATE_FAIL = 'article/CREATE_FAIL'
const GETIMAGES = 'env/GETIMAGES'
const GETIMAGES_SUCCESS = 'env/GETIMAGES_SUCCESS'
const GETIMAGES_FAIL = 'env/GETIMAGES_FAIL'
export {
  CREATE,
  CREATE_SUCCESS,
  CREATE_FAIL,
  GETIMAGES,
  GETIMAGES_SUCCESS,
  GETIMAGES_FAIL,
}