const GETTAGS = 'env/GETTAGS'
const GETTAGS_SUCCESS = 'env/GETTAGS_SUCCESS'
const GETTAGS_FAIL = 'env/GETTAGS_FAIL'
const GETBINGIMG = 'env/GETBINGIMG'
const GETBINGIMG_SUCCESS = 'env/GETBINGIMG_SUCCESS'
const GETBINGIMG_FAIL = 'env/GETBINGIMG_FAIL'
export {
  GETTAGS,
  GETTAGS_SUCCESS,
  GETTAGS_FAIL,
  GETBINGIMG,
  GETBINGIMG_SUCCESS,
  GETBINGIMG_FAIL,
}