const GETARTICLES = 'home/GETARTICLES'
const GETARTICLES_SUCCESS = 'home/GETARTICLES_SUCCESS'
const GETARTICLES_FAIL = 'home/GETARTICLES_FAIL'

export {
  GETARTICLES,
  GETARTICLES_SUCCESS,
  GETARTICLES_FAIL,
}