



const SIGNIN = 'user/SIGNIN'
const SIGNIN_SUCCESS = 'user/SIGNIN_SUCCESS'
const SIGNIN_FAIL = 'user/SIGNIN_FAIL'
const SIGNUP = 'user/SIGNUP'
const SIGNUP_SUCCESS = 'user/SIGNUP_SUCCESS'
const SIGNUP_FAIL = 'user/SIGNUP_FAIL'
const USERINFO = 'user/USERINFO'
const USERINFO_SUCCESS = 'user/USERINFO_SUCCESS'
const USERINFO_FAIL = 'user/USERINFO_FAIL'

export {
  SIGNIN,
  SIGNIN_SUCCESS,
  SIGNIN_FAIL,
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  USERINFO,
  USERINFO_SUCCESS,
  USERINFO_FAIL,
}